### PR TITLE
Update locations

### PR DESCRIPTION
**Pull request by danamansana**
Updates the locations csv and jsonld with some new locations received from ILS. This is based on the following assumptions:

- the location code and name we are given correspond to `skos:notation` and `skos:prefLabel`.
- `skos:altLabel` is the same as `skos:prefLabel` for the new entries
- `nypl:collectionType` is obtained by taking the first two letters of the location code, and using that as the parent location. If the parent location exists, the parent location dictates the collection type.
- `dcterms:isPartOf` is the parent location, if it exists.
- `nypl:requestable` is false
- `nypl:allowSierraHolds` is true
- everything else is blank.

The existing location code mappings are unchanged, except 
- the list is now alphabetized
- `mmzzz` occurred twice, now the list only contains the copy without the phrase `error code` in the name

the json-ld was generated from the csv using the corresponding python script.
I've updated the changelog and the README.

### CODE REVIEW

**Comment by nonword** [comment]
Do you have any way to show a semantic diff? I think we need a general way to validate big changes like this. I can visually inspect the CSV diff and it does look like the changes are entirely additive except for reordering a dozen entries that were previously at the bottom. If you used the python tool to generate the JSON-LD file, that provides decent assurance that the new file contains only *additions*. I just wish we had a simple, documented method for inspecting that diff to confirm - for example - that we're not overwriting a rogue change made to the JSON-LD that was not also made to the CSV. I've yet to find a tool that produces a useful report on two objects this large. Have you?

**Comment by mwbenowitz** [comment]
@danamansana @nonword Here is the output of the script to scan for changes/additions/deletions to the JSON-LD locations file. It picked up three location codes with changes. I don't know if these changes are valid or intended.

```
Keys Added: 566
Keys Deleted: 0
Keys Altered: 3

ALTERED KEY: mmzzz
Attribute: root['skos:prefLabel']
Old Value: Mid-Manhattan
New Value: ['Mid-Manhattan', 'Mid-Manhattan (error code)']

ALTERED KEY: qcmj2
Attribute(Pos): root['nypl:deliverableTo'][4]
Removed Value: {'@id': 'nyplLocation:mal17'}

ALTERED KEY: lsdd2
Attribute: root['nypl:recapCustomerCode']['@id']
Old Value: http://data.nypl.org/recapCustomerCodes/NI
New Value: http://data.nypl.org/recapCustomerCodes/OI
Attribute: root['nypl:deliverableTo']['@id']
Old Value: nyplLocation:lsdd2
New Value: nyplLocation:lsc-oi
Attribute: root['skos:altLabel']
Old Value: Library Services Center - Special Formats Processing
New Value: Library Services Center - DIU
Attribute: root['@id']
Old Value: nyplLocation:lsdd2
New Value: nyplLocation:lsc-oi
Attribute: root['skos:prefLabel']
Old Value: Library Services Center - Special Formats Processing
New Value: Library Services Center - DIU
```

**Comment by danamansana** [comment]
Thanks, I am going to look into this. On first glance,

1. I expect some change to `mmzzz` for reasons noted in the comment
2. I don't know where `qcmj2` is coming from
3. It looks like `lsdd2` is for some reason taking values from the line that was deleted immediately after it. Not sure why.

**Comment by danamansana** [comment]
When I run the validation script now, the only altered value I see is `lsdd2`, which as I understand it (following discussion with Paul), is correct to change.

**Review by nonword — APPROVED** [review]
On the assumption that this is strictly additive* I approve

\* One non-additive known change is fixing the `skos:notation` for "nyplLocation:lsc-oi" from "lsdd2" to "ls-oi". (Assumed to be a typo.)

**Review by mwbenowitz — APPROVED** [review]

**Comment by mwbenowitz** [comment]
@danamansana Is this ready to be merged, or is there anything left that needs to be checked?

**Pull request merged**
