### PR TITLE
Add some series, title fields

### PR DESCRIPTION
**Pull request by nonword**
Adds some new bib mappings:
  800, 810, 811, 490: map to Series statement (seriesStatement).
  730, 830: map to Uniform title (uniformTitle).
  740: map to Alternative title (titleAlt)
  247: new field: Former title (formerTitle)

### CODE REVIEW

**Comment by nonword** [comment]
Worth noting this may introduce the marc tag that looks the most like a screaming face when you turn your head sideways:

```
810
```

**Comment by katesweeney** [comment]
This is true, and I didn't think one could win a sprint, but you just won the sprint.

**Comment by saverkamp** [comment]
I don't see 811 under `seriesStatement`. Other than that, looks good to go!

**Comment by nonword** [comment]
@saverkamp whoops. good catch. Thanks. Fixed.

**Pull request merged**
