### PR TITLE
Add CHANGELOG.md to annotate tagged versions

### PR DESCRIPTION
**Pull request by gkallenberg**
As part of my effort to help document some things, I've gone ahead and added a changelog to provide a brief list of changes included in versions which should help to give an "at-a-glance" view. Let me know if more information is needed or if you think pre-release information would also be helpful to include or if this is something that is not quite necessary.

### CODE REVIEW

**Comment by saverkamp** [comment]
This is great and totally makes sense to have, but what is the difference between having a changelog file and referring to the releases page (which, of course, would require people to annotate their tags)?

**Comment by gkallenberg** [comment]
Excellent question. To me, the changelog is more of a developer doc that gets packaged in code similar to the releases page of github. I tend to look for changelogs in other applications I use or work on as a place to show what features get introduced when or what bugs were squashed in which tag. I tend to be lazy when tagging or looking at repositories in a terminal program. I don't use the annotation option when tagging and when I list tags, I don't use the option to show the annotations so I only see the names of the tags without any of the information.

This could be a topic to discuss across the team as to what the best practice is or should be regarding annotations/logs for tags. Or, everyone else is doing this already and I need to incorporate adding proper annotations in my routine. Changelogs, to me, seem like a more obvious place to look for release notes and may have more information than an annotation on a tag may include. ??

**Comment by nonword** [comment]
I like this. We've discussed CHANGELOGs here: https://github.com/NYPL/engineering-general/pull/54. Your addition here seems to pretty closely match the recommendation there.

@saverkamp raises a good point and one I've wondered about; A CHANGELOG of some form is important, but I wonder if we can leverage existing git infrastructure to ensure it's kept in sync with our tags. If, instead of updating a CHANGELOG, we created a new Release with every tag we pushed, that'd have the benefit of easy linking to zip archives, commit listings, and diffs for each tag.. Only problem is, as GK points out, I don't see CLI support outside of the Github REST api.. so maybe that's a nonstarter. Or maybe, like PRs, it's just something we have to use a browser to do. I could go either way.

**Comment by nonword** [comment]
@saverkamp Okay if we merge this so that it's in line with our engineering standards? I'm open to also publishing Releases for this repo - in effect annotating nypl-core versions in both the CHANGELOG and the Releases tab.

**Comment by nonword** [comment]
@gkallenberg I added a commit back-filling changelog entries up to latest. Also added a note about keeping it up to date as part of the tag/deploy process in README. See https://github.com/NYPL/nypl-core/pull/26/commits/1cff98c73e5d66c96fa918f73239869c1a86eb13 for details.

**Comment by gkallenberg** [comment]
@nonword Excellent! Thanks, all. I'll run the merge for this.

**Pull request merged**
