### PR TITLE
Adds rebuilt Bib Notes mappings with updated types

### PR DESCRIPTION
**Pull request by nonword**
Amends mappings/recap-discovery/field-mapping-bib.json with updated
mappings for bib Note field

### CODE REVIEW

**Comment by katesweeney** [comment]
MARC field 542 is mapped to an incorrect label, it should be "Note." Mapping for the affected fields should be:

542 = "Note"
544 = "Location of Other Archival Materials"

Also, 588 should be changed

588 = "Note"

Although I like the label "Source of Description" for 588, it might conflict with other contents in 588 fields. WebPAC maps 588 to "Note." See example: http://catalog.nypl.org/record=b10091862, the last 2 entries under "Note" are both 588 fields.

WebPAC maps 542 to "Note," see example: http://ilsstaff.nypl.org/record=b10068873 ("Copyright 1890 by F.C. Briggs."). 542 is a copyright status note with highly detailed options: http://loc.gov/marc/bibliographic/bd542.html. I'd like to leave 542 mapped to "Note" for now; let's get staff input on what the (subfield-determined?) label should really be or if "Note" is sufficient.

Otherwise, looks great. As discussed, we can handle indicator- and subfield-determined labels down the line (e.g. 511 Performer vs. Cast and 555 Indexes vs. Finding Aids).

**Comment by saverkamp** [comment]
Thanks, Kate. I couldn't find those fields in webpub.def or the all-fields record, so I gave them labels based on the MARC field name. The problem with mapping them all to Note is that we will no longer preserve any semantic distinction, they'll all get lumped in with all of the other 500 general notes. (We're using the note type as the label in the data store.) Even if they're all displayed together under "Note" there may be cases where we want to treat them as separate note types. I would rather we give instruction to the front-end devs on how to label and display these particular note types in the record display (i.e. under "Note"), so we can preserve the distinction in the data store.

**Comment by katesweeney** [comment]
Thanks, Shawn -- that makes sense. I'll create a ticket for the frontend aspect of this; please feel free to adjust any technical details (or let me know if you'd like to discuss further): https://jira.nypl.org/browse/SCC-384

**Comment by katesweeney** [comment]
Also, to clarify: the code needs to be corrected for 542/544 (542 is mislabeled, 544 is not in the code).

542 = "Copyright Status"
544= "Location of Other Archival Materials"

**Comment by saverkamp** [comment]
544 is there, it's just not visible in the snippet. (You can see it in the full file view.)
For 542, the current label is "Information Related to Copyright Status". Did you want to shorten it to just "Copyright Status"?

**Pull request merged**
